version: '2'
services:
  stcode-admin:
    image: stcode/admin
    ports:
      - "8080:8080"
    environment:
      - spring.profiles.active=dev
  stcode-api:
    image: stcode/api
    ports:
      - "8081:8081"
    environment:
      - spring.profiles.active=dev